### PR TITLE
Set up test suite

### PR DESCRIPTION
**Pull request by Fabianopb**
This PR configures a test suite with Jest and Enzyme for the project.
* `yarn test` will run all the tests and show the coverage report
* `yarn test:watch [fileName]` can be used to watch test development in real time for a file(s)
* A simple test was created for each component

As a next step after this PR gets merged, I'd recommend a refactor on the logic of `TypingTest.js` and writing related tests to get a good coverage in that component.

Cheers!

### CODE REVIEW

**Comment by Fabianopb** [comment]
Sec, there were some changes in the `master` branch, I'm merging and fixing!

**Comment by Fabianopb** [comment]
Sweet, all checks passed and Travis is happy!

**Comment by ummahusla** [comment]
I strongly disagree here:

`"test": "react-scripts test --env=jsdom --coverage --colors"`

I think `coverage` section shoudln't be run on every go, instead it should have its own npm script like `test:coverage`.

**Comment by Fabianopb** [comment]
@ummahusla a matter of taste, but sure, why not? Commited.

**Comment by Scoombe** [comment]
@Fabianopb Awesome! Merged.

**Pull request merged**
